### ISSUE TITLE
[Identifier] serializer group not being used for User

### ISSUE THREAD

**Issue by kochen** [jorge07/ddd-playground#26]
The `[Identifier]` serializer group not being used for User.
In fact `AggregatedRootId` is also not using it:
```
Leos\Domain\Common\ValueObject\AggregateRootId:
    properties:
        uuid:
            expose: true
            groups: [Basic]
```

It **is** being used by the transition `id`, but the user is not using that ;)
